apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monapp-ingress
  annotations:
    networking.gke.io/managed-certificates: monapp-managed-cert
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 80
  rules:
  - host: norma.miicom.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80